# Generated by Django 4.0.1 on 2022-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='cases',
            new_name='caseInput',
        ),
        migrations.AddField(
            model_name='challenge',
            name='caseOutput',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
